#include "ReactDOMContainer.h"

// Auto-generated by scripts/translate-react.js
// Source: react-main/packages/react-dom-bindings/src/client/ReactDOMContainer.js

namespace react {

// lines 19-29
void isValidContainer() {
  // TODO: Translate implementation.
}

} // namespace react
