#pragma once

// Auto-generated by scripts/translate-react.js
// Source: react-main/packages/react-reconciler/src/ReactTypeOfMode.js

#include <cstdint>

namespace react {

using TypeOfMode = std::uint32_t;

inline constexpr TypeOfMode NoMode = 0b0000000;
inline constexpr TypeOfMode ConcurrentMode = 0b0000001;
inline constexpr TypeOfMode ProfileMode = 0b0000010;
inline constexpr TypeOfMode StrictLegacyMode = 0b0001000;
inline constexpr TypeOfMode StrictEffectsMode = 0b0010000;
inline constexpr TypeOfMode SuspenseyImagesMode = 0b0100000;

} // namespace react
