#include "ReactWorkTags.h"

// Auto-generated by scripts/translate-react.js
// Source: react-main/packages/react-reconciler/src/ReactWorkTags.js

namespace react {

static_assert(toInt(WorkTag::FunctionComponent) == 0,
	"WorkTag::FunctionComponent must match ReactWorkTags.js");
static_assert(toInt(WorkTag::ClassComponent) == 1,
	"WorkTag::ClassComponent must match ReactWorkTags.js");
static_assert(toInt(WorkTag::HostRoot) == 3,
	"WorkTag::HostRoot must match ReactWorkTags.js");
static_assert(toInt(WorkTag::HostComponent) == 5,
	"WorkTag::HostComponent must match ReactWorkTags.js");
static_assert(toInt(WorkTag::SuspenseComponent) == 13,
	"WorkTag::SuspenseComponent must match ReactWorkTags.js");
static_assert(toInt(WorkTag::ViewTransitionComponent) == 30,
	"WorkTag::ViewTransitionComponent must match ReactWorkTags.js");
static_assert(toInt(WorkTag::ActivityComponent) == 31,
	"WorkTag::ActivityComponent must match ReactWorkTags.js");

} // namespace react
