#include "ReactFiberFlags.h"

// Auto-generated by scripts/translate-react.js
// Source: react-main/packages/react-reconciler/src/ReactFiberFlags.js

namespace react {

static_assert(NoFlags == 0u, "NoFlags must match ReactFiberFlags.js");
static_assert(PerformedWork == 1u, "PerformedWork must match ReactFiberFlags.js");
static_assert(Placement == 2u, "Placement must match ReactFiberFlags.js");
static_assert(Update == 4u, "Update must match ReactFiberFlags.js");
static_assert(DidCapture == 128u, "DidCapture must match ReactFiberFlags.js");
static_assert(Hydrating == 4096u, "Hydrating must match ReactFiberFlags.js");
static_assert(LifecycleEffectMask ==
		(Passive | Update | Callback | Ref | Snapshot | StoreConsistency),
	"LifecycleEffectMask must match ReactFiberFlags.js");
static_assert(HostEffectMask == 0b0000000000000000111111111111111u,
	"HostEffectMask must match ReactFiberFlags.js");
static_assert(PassiveMask == (Passive | Visibility | ChildDeletion),
	"PassiveMask must match ReactFiberFlags.js");
static_assert(StaticMask ==
		(LayoutStatic | PassiveStatic | RefStatic | MaySuspendCommit |
			ViewTransitionStatic | ViewTransitionNamedStatic),
	"StaticMask must match ReactFiberFlags.js");

} // namespace react
