#pragma once

// Auto-generated by scripts/translate-react.js
// Source: react-main/packages/react-reconciler/src/ReactWorkTags.js

#include <cstdint>

namespace react {

enum class WorkTag : std::uint8_t {
	FunctionComponent = 0,
	ClassComponent = 1,
	IndeterminateComponent = 2,
	HostRoot = 3,
	HostPortal = 4,
	HostComponent = 5,
	HostText = 6,
	Fragment = 7,
	Mode = 8,
	ContextConsumer = 9,
	ContextProvider = 10,
	ForwardRef = 11,
	Profiler = 12,
	SuspenseComponent = 13,
	MemoComponent = 14,
	SimpleMemoComponent = 15,
	LazyComponent = 16,
	IncompleteClassComponent = 17,
	DehydratedFragment = 18,
	SuspenseListComponent = 19,
	ScopeComponent = 21,
	OffscreenComponent = 22,
	LegacyHiddenComponent = 23,
	CacheComponent = 24,
	TracingMarkerComponent = 25,
	HostHoistable = 26,
	HostSingleton = 27,
	IncompleteFunctionComponent = 28,
	Throw = 29,
	ViewTransitionComponent = 30,
	ActivityComponent = 31,
};

inline constexpr WorkTag FunctionComponent = WorkTag::FunctionComponent;
inline constexpr WorkTag ClassComponent = WorkTag::ClassComponent;
inline constexpr WorkTag IndeterminateComponent = WorkTag::IndeterminateComponent;
inline constexpr WorkTag HostRoot = WorkTag::HostRoot;
inline constexpr WorkTag HostPortal = WorkTag::HostPortal;
inline constexpr WorkTag HostComponent = WorkTag::HostComponent;
inline constexpr WorkTag HostText = WorkTag::HostText;
inline constexpr WorkTag Fragment = WorkTag::Fragment;
inline constexpr WorkTag Mode = WorkTag::Mode;
inline constexpr WorkTag ContextConsumer = WorkTag::ContextConsumer;
inline constexpr WorkTag ContextProvider = WorkTag::ContextProvider;
inline constexpr WorkTag ForwardRef = WorkTag::ForwardRef;
inline constexpr WorkTag Profiler = WorkTag::Profiler;
inline constexpr WorkTag SuspenseComponent = WorkTag::SuspenseComponent;
inline constexpr WorkTag MemoComponent = WorkTag::MemoComponent;
inline constexpr WorkTag SimpleMemoComponent = WorkTag::SimpleMemoComponent;
inline constexpr WorkTag LazyComponent = WorkTag::LazyComponent;
inline constexpr WorkTag IncompleteClassComponent = WorkTag::IncompleteClassComponent;
inline constexpr WorkTag DehydratedFragment = WorkTag::DehydratedFragment;
inline constexpr WorkTag SuspenseListComponent = WorkTag::SuspenseListComponent;
inline constexpr WorkTag ScopeComponent = WorkTag::ScopeComponent;
inline constexpr WorkTag OffscreenComponent = WorkTag::OffscreenComponent;
inline constexpr WorkTag LegacyHiddenComponent = WorkTag::LegacyHiddenComponent;
inline constexpr WorkTag CacheComponent = WorkTag::CacheComponent;
inline constexpr WorkTag TracingMarkerComponent = WorkTag::TracingMarkerComponent;
inline constexpr WorkTag HostHoistable = WorkTag::HostHoistable;
inline constexpr WorkTag HostSingleton = WorkTag::HostSingleton;
inline constexpr WorkTag IncompleteFunctionComponent = WorkTag::IncompleteFunctionComponent;
inline constexpr WorkTag Throw = WorkTag::Throw;
inline constexpr WorkTag ViewTransitionComponent = WorkTag::ViewTransitionComponent;
inline constexpr WorkTag ActivityComponent = WorkTag::ActivityComponent;

[[nodiscard]] constexpr std::uint8_t toInt(WorkTag tag) {
	return static_cast<std::uint8_t>(tag);
}

[[nodiscard]] constexpr WorkTag workTagFromInt(std::uint8_t value) {
	return static_cast<WorkTag>(value);
}

} // namespace react
