#include "ReactFeatureFlags.h"

// Auto-generated by scripts/translate-react.js
// Source: react-main/packages/shared/ReactFeatureFlags.js

namespace react {

static_assert(enableHydrationLaneScheduling,
	"Expected hydration lane scheduling to be enabled by default.");
static_assert(ownerStackLimit == 10000,
	"ownerStackLimit must match ReactFeatureFlags.js (1e4)");

} // namespace react
