#pragma once

// Auto-generated by scripts/translate-react.js
// Source: react-main/packages/shared/ReactFeatureFlags.js

#ifndef REACTCPP_ENABLE_EXPERIMENTAL
#define REACTCPP_ENABLE_EXPERIMENTAL 0
#endif

#ifndef REACTCPP_ENABLE_PROFILE
#define REACTCPP_ENABLE_PROFILE 0
#endif

namespace react {

inline constexpr bool kExperimentalBuild = REACTCPP_ENABLE_EXPERIMENTAL != 0;
inline constexpr bool kProfileBuild = REACTCPP_ENABLE_PROFILE != 0;

inline constexpr bool enableHydrationLaneScheduling = true;
inline constexpr bool disableSchedulerTimeoutInWorkLoop = false;
inline constexpr bool enableSuspenseCallback = false;
inline constexpr bool enableScopeAPI = false;
inline constexpr bool enableCreateEventHandleAPI = false;
inline constexpr bool enableLegacyFBSupport = false;

inline constexpr bool enableYieldingBeforePassive = false;
inline constexpr bool enableThrottledScheduling = false;

inline constexpr bool enableLegacyCache = kExperimentalBuild;
inline constexpr bool enableAsyncIterableChildren = kExperimentalBuild;
inline constexpr bool enableTaint = kExperimentalBuild;
inline constexpr bool enablePostpone = kExperimentalBuild;
inline constexpr bool enableHalt = kExperimentalBuild;
inline constexpr bool enableViewTransition = kExperimentalBuild;
inline constexpr bool enableGestureTransition = kExperimentalBuild;
inline constexpr bool enableScrollEndPolyfill = kExperimentalBuild;
inline constexpr bool enableSuspenseyImages = false;
inline constexpr bool enableFizzBlockingRender = kExperimentalBuild;
inline constexpr bool enableSrcObject = kExperimentalBuild;
inline constexpr bool enableHydrationChangeEvent = kExperimentalBuild;
inline constexpr bool enableDefaultTransitionIndicator = kExperimentalBuild;

inline constexpr bool enableObjectFiber = false;
inline constexpr bool enableTransitionTracing = false;
inline constexpr bool enableLegacyHidden = false;
inline constexpr bool enableSuspenseAvoidThisFallback = false;
inline constexpr bool enableCPUSuspense = kExperimentalBuild;
inline constexpr bool enableNoCloningMemoCache = false;
inline constexpr bool enableUseEffectEventHook = kExperimentalBuild;
inline constexpr bool enableFizzExternalRuntime = kExperimentalBuild;

inline constexpr bool alwaysThrottleRetries = true;
inline constexpr bool passChildrenWhenCloningPersistedNodes = false;
inline constexpr bool enablePersistedModeClonedFlag = false;
inline constexpr bool enableEagerAlternateStateNodeCleanup = true;

inline constexpr bool enableRetryLaneExpiration = false;
inline constexpr int retryLaneExpirationMs = 5000;
inline constexpr int syncLaneExpirationMs = 250;
inline constexpr int transitionLaneExpirationMs = 5000;

inline constexpr bool enableInfiniteRenderLoopDetection = false;
inline constexpr bool enableFragmentRefs = kExperimentalBuild;

inline constexpr bool renameElementSymbol = true;
inline constexpr bool enableHiddenSubtreeInsertionEffectCleanup = false;
inline constexpr bool disableLegacyContext = true;
inline constexpr bool disableLegacyContextForFunctionComponents = true;
inline constexpr bool enableMoveBefore = false;
inline constexpr bool disableClientCache = true;
inline constexpr bool enableReactTestRendererWarning = true;
inline constexpr bool disableLegacyMode = true;

inline constexpr bool disableCommentsAsDOMContainers = true;
inline constexpr bool enableTrustedTypesIntegration = false;
inline constexpr bool disableInputAttributeSyncing = false;
inline constexpr bool disableTextareaChildren = false;

inline constexpr bool enableProfilerTimer = kProfileBuild;
inline constexpr bool enableComponentPerformanceTrack = kExperimentalBuild;
inline constexpr bool enableSchedulingProfiler =
	!enableComponentPerformanceTrack && kProfileBuild;
inline constexpr bool enableProfilerCommitHooks = kProfileBuild;
inline constexpr bool enableProfilerNestedUpdatePhase = kProfileBuild;
inline constexpr bool enableAsyncDebugInfo = true;
inline constexpr bool enableUpdaterTracking = kProfileBuild;

inline constexpr int ownerStackLimit = 10000;

} // namespace react
